# -*- coding: utf-8 -*-
"""FMNIST interactive umap demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qpr674SsZQ-4NI7SpIJkg82yF8fIqkj8
"""

from fileinput import filename
from turtle import title
import sklearn.datasets
import pandas as pd
import numpy as np
import umap.umap_ as umap
import umap.plot
import seaborn as sns
from bokeh.plotting import save, figure, show
from matplotlib import pyplot
from matplotlib.gridspec import GridSpec
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
import mpld3

# Create HTML file with output plot using Bokeh
umap.plot.output_file(filename='index.html', title='Interactive UMAP of FMNIST')

# Obtain FMNIST (Fashion MNIST) dataset
fmnist = sklearn.datasets.fetch_openml('Fashion-MNIST')

# Train new mapper object on the data
mapper = umap.UMAP().fit(fmnist.data[:10])

# Create the hover information as a dataframe
# In this case, include the index of the point, its target number, and the actual name of the type of
# fashion item that target corresponds to
hover_data = pd.DataFrame({'index': np.arange(30000),
                           'label': fmnist.target[:30000]})
hover_data['item'] = hover_data.label.map(
    {
        '0': 'T-shirt/top',
        '1': 'Trouser',
        '2': 'Pullover',
        '3': 'Dress',
        '4': 'Coat',
        '5': 'Sandal',
        '6': 'Shirt',
        '7': 'Sneaker',
        '8': 'Bag',
        '9': 'Ankle Boot',
    }
)

# Interactive UMAP using bokeh
p = umap.plot.interactive(
    mapper, labels=fmnist.target[:30000], hover_data=hover_data, point_size=10)

save(p)